In [1]:
mylist = ["Jitin", 5, 60, 6.5,"abc", 5, 5.9,4,5,8,1,2]
tuple1 = tuple(mylist)
print(type(tuple1))

<class 'tuple'>


In [18]:
list1 = [1,6,9,2,4]
list2 = [4,6,7,8,9]

list3 = [list1] + [list2]
list3[1][2]


7

In [20]:
import numpy as np
list1 = [1,2,3,4,5]
A = np.array(list1)
print(A)

[1 2 3 4 5]


In [26]:
list1 = [3,4,6,7,8,9,33,43,53,63]
#list1[::-1]
#list1[1 : 5]
#list1[1:6:2]
list1[1:]
list1[:6]

[3, 4, 6, 7, 8, 9]

In [57]:
import numpy as np
list1 = [[2,3,4,5],[23,45,67,89],[3,4,6,7]]
A = np.array(list1)
print(A)
print(A[1])
print(A[2])
print(A[-1])
print(A[1][2])
print(A[1][1])
print(A[-1][1])
print(A[0][2])
print(A[0][0])
print(A[-1][-2])
A[0][0] = 12
A1 = A + A
print(A1)
A3 = np.array([A1, A1, A1])
print(A3[0][0][0])

[[ 24   6   8  10]
 [ 46  90 134 178]
 [  6   8  12  14]]
24


In [59]:
import numpy as np
s1 = np.array([[2,3,4],[5,6,7],[4,3,8]])
s2 = np.array([[8,2,1],[0,-5,4],[7,3,1]])
s3 = s1 + s2 
print(s3)
print(s1 @ s2)


[[10  5  5]
 [ 5  1 11]
 [11  6  9]]
[[44  1 18]
 [89  1 36]
 [88 17 24]]
