In [58]:
list1 = [1,2,3,4,True]
list2 = list1 + list1
print(list2)
# list3 = list1 + 2
# print(list3) #Type error
list4 = [1,2,3,4]
# list5 = list4 + 2
# print(list5) #Type error
list6 = list1 + list4
list7 = list1, list4
print(list6)
print(list7) #We will get tuple of lists
print(type(list7))
list8 = [list1, list4] #We will get list of lists
print(list8)

[1, 2, 3, 4, True, 1, 2, 3, 4, True]
[1, 2, 3, 4, True, 1, 2, 3, 4]
([1, 2, 3, 4, True], [1, 2, 3, 4])
<class 'tuple'>
[[1, 2, 3, 4, True], [1, 2, 3, 4]]


In [59]:
"""
Numpy:-
    Used for numerical data. made with C and can be used to create array. can perform defferent operation on numerical data.
"""

'\nNumpy:-\n    Used for numerical data. made with C and can be used to create array. can perform defferent operation on numerical data.\n'

In [60]:
import numpy as np

list1 = [1,2,3,4,5]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [61]:
arr2 = arr1 + 2
print(arr2)

[3 4 5 6 7]


In [62]:
print(arr1.shape)

(5,)


In [63]:
list2 = [[1,2,3,4],[5,6,7,8],[9,0,8,7]]
arr3 = np.array(list2)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 8 7]]


In [64]:
print(arr3.shape)

(3, 4)


In [65]:
data = np.array([
    [1, 85, 5, 90],
    [2, 78, 4, 85],
    [3, 92, 6, 95],
    [4, 60, 2, 70],
    [5, 75, 3, 80]
    ])
print(data)
print(data.shape)
print(data[0])
print(data[:,1]) # Print index 1 colomun
print(data[1:4]) # Print specific value metrix or rows

[[ 1 85  5 90]
 [ 2 78  4 85]
 [ 3 92  6 95]
 [ 4 60  2 70]
 [ 5 75  3 80]]
(5, 4)
[ 1 85  5 90]
[85 78 92 60 75]
[[ 2 78  4 85]
 [ 3 92  6 95]
 [ 4 60  2 70]]


In [66]:
data[:, 1] = data[:, 1] + 5
print(data)

[[ 1 90  5 90]
 [ 2 83  4 85]
 [ 3 97  6 95]
 [ 4 65  2 70]
 [ 5 80  3 80]]


In [67]:
# numeric operations
print(np.mean(data[:,1]))
print(np.max(data[:,1]))
print(np.std(data[:,1]))

83.0
97
10.75174404457249


In [68]:
high_scores = data[data[:,1] > 80] #Pipeline, Aggregation
print(high_scores)

[[ 1 90  5 90]
 [ 2 83  4 85]
 [ 3 97  6 95]]


In [69]:
"""
Aggregation:-
    Aggregation refers to collecting multiple values and computing a single summary result from them.
    It's a fundamental concept used in data processing, databases, and OOP.
"""

"\nAggregation:-\n    Aggregation refers to collecting multiple values and computing a single summary result from them.\n    It's a fundamental concept used in data processing, databases, and OOP.\n"

In [70]:
marks = data[:, 1]
print(marks.reshape(5, 1))
print(type(marks))

[[90]
 [83]
 [97]
 [65]
 [80]]
<class 'numpy.ndarray'>


In [71]:
import pandas as pd 
df = pd.DataFrame(data, columns = ["ID", "Marks", "Hours", "Attendance"])
print(df)
print(type(df))

   ID  Marks  Hours  Attendance
0   1     90      5          90
1   2     83      4          85
2   3     97      6          95
3   4     65      2          70
4   5     80      3          80
<class 'pandas.core.frame.DataFrame'>


In [72]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          5 non-null      int64
 1   Marks       5 non-null      int64
 2   Hours       5 non-null      int64
 3   Attendance  5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes
None


In [73]:
print(df.describe())

             ID      Marks     Hours  Attendance
count  5.000000   5.000000  5.000000    5.000000
mean   3.000000  83.000000  4.000000   84.000000
std    1.581139  12.020815  1.581139    9.617692
min    1.000000  65.000000  2.000000   70.000000
25%    2.000000  80.000000  3.000000   80.000000
50%    3.000000  83.000000  4.000000   85.000000
75%    4.000000  90.000000  5.000000   90.000000
max    5.000000  97.000000  6.000000   95.000000


In [74]:
df["Performance"] = df["Marks"] > 80
print(df)

   ID  Marks  Hours  Attendance  Performance
0   1     90      5          90         True
1   2     83      4          85         True
2   3     97      6          95         True
3   4     65      2          70        False
4   5     80      3          80        False


In [75]:
sorted_df = df.sort_values(by = "Marks", ascending = False)
print(sorted_df)

   ID  Marks  Hours  Attendance  Performance
2   3     97      6          95         True
0   1     90      5          90         True
1   2     83      4          85         True
4   5     80      3          80        False
3   4     65      2          70        False


In [76]:
df.loc[2, "Marks"] = None
print(df)

   ID  Marks  Hours  Attendance  Performance
0   1   90.0      5          90         True
1   2   83.0      4          85         True
2   3    NaN      6          95         True
3   4   65.0      2          70        False
4   5   80.0      3          80        False


In [78]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

   ID  Marks  Hours  Attendance  Performance
0   1   90.0      5          90         True
1   2   83.0      4          85         True
2   3   79.5      6          95         True
3   4   65.0      2          70        False
4   5   80.0      3          80        False


In [79]:
df["Category"] = ["A", "B", "A", "B", "A"]
print(df)

   ID  Marks  Hours  Attendance  Performance Category
0   1   90.0      5          90         True        A
1   2   83.0      4          85         True        B
2   3   79.5      6          95         True        A
3   4   65.0      2          70        False        B
4   5   80.0      3          80        False        A


In [80]:
print(df.groupby("Category")["Marks"].mean())

Category
A    83.166667
B    74.000000
Name: Marks, dtype: float64


In [82]:
df = pd.DataFrame({
    "date"    : ["2024-01-15", "2024-02-20", "2024-03-05"],
    "price"   : ["₹1,200", "₹3,500", "₹800"],
    "in_stock": ["Yes", "No", "Yes"],
    "qty"     : ["10", "25", "5"],
})
print(df)

         date   price in_stock qty
0  2024-01-15  ₹1,200      Yes  10
1  2024-02-20  ₹3,500       No  25
2  2024-03-05    ₹800      Yes   5


In [83]:
df["qty"] = df["qty"].astype(int)
print(df)

         date   price in_stock  qty
0  2024-01-15  ₹1,200      Yes   10
1  2024-02-20  ₹3,500       No   25
2  2024-03-05    ₹800      Yes    5
